### ISSUE TITLE
Pre-prod checklist

### ISSUE THREAD

**Issue by Lucaterre** [chartes/endp-person-app#4]
- [x] Finir les tests #2 
- [x] Revoir les data (dataiku) => bug IDS
- [x] commenter la feature mot de passe oublié
- [x] Tester requirements.txt
- [x] Tester les commandes CLI
